"""add settings and notification models

Revision ID: d3f417cedbb6
Revises: aa8dc072e823
Create Date: 2026-04-16 12:10:14.046453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3f417cedbb6'
down_revision: Union[str, Sequence[str], None] = 'aa8dc072e823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('reminder_notifications', sa.Boolean(), nullable=False),
    sa.Column('application_updates', sa.Boolean(), nullable=False),
    sa.Column('interview_reminders', sa.Boolean(), nullable=False),
    sa.Column('offer_notifications', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('timeline_events', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline_events', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_user_is_read', table_name='notifications')
    op.drop_index('idx_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
