"""create applications table

Revision ID: efeea58e6057
Revises: ddc0cb054e02
Create Date: 2026-03-08 09:39:52.499360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efeea58e6057'
down_revision: Union[str, Sequence[str], None] = 'ddc0cb054e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('applications', 'salary_mentioned',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="salary_mentioned::integer")
    op.add_column('interview_preps', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('interview_preps', sa.Column('outcome', sa.String(length=50), nullable=True))
    op.add_column('interview_preps', sa.Column('ai_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_preps', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('idx_interviewprep_application', 'interview_preps', ['application_id'], unique=False)
    op.add_column('reminders', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('reminders', sa.Column('application_id', sa.UUID(), nullable=False))
    op.add_column('reminders', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('reminders', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('reminders', sa.Column('remind_at', sa.DateTime(), nullable=False))
    op.add_column('reminders', sa.Column('is_sent', sa.Boolean(), nullable=False))
    op.add_column('reminders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index('idx_is_sent_remind_at', 'reminders', ['is_sent', 'remind_at'], unique=False)
    op.create_foreign_key(None, 'reminders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reminders', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('screeninganswers', sa.Column('application_id', sa.UUID(), nullable=False))
    op.add_column('screeninganswers', sa.Column('question', sa.Text(), nullable=False))
    op.add_column('screeninganswers', sa.Column('answer', sa.Text(), nullable=False))
    op.add_column('screeninganswers', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('screeninganswers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_screeninganswers_application_id'), 'screeninganswers', ['application_id'], unique=False)
    op.create_foreign_key(None, 'screeninganswers', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.add_column('timeline_events', sa.Column('application_id', sa.UUID(), nullable=False))
    op.add_column('timeline_events', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('timeline_events', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('timeline_events', sa.Column('metadataa', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('timeline_events', sa.Column('event_at', sa.DateTime(), nullable=False))
    op.create_index('idx_application_event_time', 'timeline_events', ['application_id', 'event_at'], unique=False)
    op.create_foreign_key(None, 'timeline_events', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeline_events', type_='foreignkey')
    op.drop_index('idx_application_event_time', table_name='timeline_events')
    op.drop_column('timeline_events', 'event_at')
    op.drop_column('timeline_events', 'metadataa')
    op.drop_column('timeline_events', 'title')
    op.drop_column('timeline_events', 'event_type')
    op.drop_column('timeline_events', 'application_id')
    op.drop_constraint(None, 'screeninganswers', type_='foreignkey')
    op.drop_index(op.f('ix_screeninganswers_application_id'), table_name='screeninganswers')
    op.drop_column('screeninganswers', 'created_at')
    op.drop_column('screeninganswers', 'question_type')
    op.drop_column('screeninganswers', 'answer')
    op.drop_column('screeninganswers', 'question')
    op.drop_column('screeninganswers', 'application_id')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_index('idx_is_sent_remind_at', table_name='reminders')
    op.drop_column('reminders', 'created_at')
    op.drop_column('reminders', 'is_sent')
    op.drop_column('reminders', 'remind_at')
    op.drop_column('reminders', 'description')
    op.drop_column('reminders', 'title')
    op.drop_column('reminders', 'application_id')
    op.drop_column('reminders', 'user_id')
    op.drop_index('idx_interviewprep_application', table_name='interview_preps')
    op.drop_column('interview_preps', 'created_at')
    op.drop_column('interview_preps', 'ai_suggestions')
    op.drop_column('interview_preps', 'outcome')
    op.drop_column('interview_preps', 'notes')
    op.alter_column('applications', 'salary_mentioned',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
